RESPONSES = [
    "Its ChocolateLab",
    "Why does everyone always want to do things at dinner time??",
    "Nah fuck that noise I am not giving up prime time in the middle of my last day before law school before this",
    "Listen… if you use my name to find my mugshot"
    "You’re a bully",
    "If I’m back into the community I’d love to That would be really nice? But I guess I’m being kicked out?",
    "Chill",
    "? Because I left the server briefly?",
    "And you put me in here knowing that . This is weird to do to someone you ASKED to come back You specifically asked me to come back",
    "So all the history you try and build up and everything just goes out the window?",
    "Can’t a man change his mind?",
    "It hasn’t even been 24 hours lmao",
    "I already played my next week match Why you replacing me like that",
    "Resttalk body press",
    "*ChocolateLab joined the party.* I want my team back",
    "I don’t want to think about this for a while if I can help it",
    "But I had to play around worst case scenario",
    "@Ebastia12 can we play tonight?",
    "If you weren’t in this game keep your opinions to yourself",
    "STILL LUCK",
    "Why do I even bother?",
    "Fuck this",
    "He gets a lucky ass burn that brings me in range of shadow sneak from brambleghast",
    "Gets a fucking crit",
    "Absolute fucking joke of a game",
    "He didn’t even bring the right mons He had Mega Audino and didn’t even fucking bring it",
    "Hold on whats the stupid command",
    "You have a long history of being rude, dismissive, and disrespctful to me. I will not apologize for these two weeks being my first two weeks of law school and wanting to prioritize that over this. It will get better, so its silly to drop over it, but I shouldn’t have to “give notice” so you can spend 10 hours building for a 15 minute match. People spend too long in prep. If you can’t prep in less than a day you need to re-examine that. And this is not how it has typically worked in practice and you know it I will not engage with you further and if you had a modicum of decency you would refrain from contacting me or joining my matches AND talking shit in the chat again in the future as I have ALREADY asked you politely not to do in the future, which you ignored then.",
    "The week begins today. I’m not expecting him to play “before the week begins” And I don’t know why the peanut gallery has to give their opinions on my scheduling anyways. This is between me and my opponent to figure out.",
    "I’m not scheduling for a week before the week begins.",
    "Later evenings EST. Weekdays Friday, Saturday, Sunday are out of the question",
    "Tonight.",
    "I don’t like to gamble but I would love to take a bet that Goff finishes the season ranked higher fantasy stats wise than him",
    "Not the right culture",
    "just DM me",
    "This upcoming week is my law school orientation adn I don’t want to fuck around with that",
    "Next weekend Saturday I will be tailgating / at football most of the day",
    "@Samky I’m taking your guy",
    "I’m going to just be annoying and take the number 1 pick overall",
    "Yeah",
    "Were we the only ones to play? Lol",
    "Ok challenge me once I’m online",
    "I need to get online",
    "Whoopsie",
    "That amount of pivoting and offensive pressure is very scary",
    "The Gaylord Gastrodons are coming for the chip this season",
    "I’m taking no prisoners",
    "A little beef is fun",
    "I tricked so that IF you were scarf you didn’t outspeed It took away your one out",
    "Pult was scarf anyways, you had already lost",
    "Bundle is trash I wouldn’t trade a bag of balls for it",
    "Bundle most overrated mon in existence It doesn’t score most OHKO without crazy hazard support Yes its fast but it rarely does much besides clean up mons something else already weakened",
    "I mean Lop is not bulky…. And took barely over half from a stab hydro pump",
    "Wow you really bet against me? Crazy",
    "The 2024 Gaylord Gastrodons",
    "Now THAT was a first game I made my predictions before I watched it",
    "Someone sure is disturbed!",
    "You have a low bar to clear for a “guilt trip”",
    "We had an agreed upon time, I could guilt trip you way harder if I wanted to kiddo. Its rude to not be ready at a time YOU set in my only week of practically completely open availability",
    "If you think that had anything to do with you you’re losing it Whats your showdown",
    "He’s online and chatting around Seems to me he ought to be prepped",
    "@Chickidy237 you done prepping yet? I guess we’re not eatingdinner as a famjly",
    "I mean I have all week off I jusr don’t like to go smack dab in the middle of dinner time",
    "Ugh We’ll have to go after then",
    "I mean want is a strong word but I can try",
    "I feel like If it isn’t in the first few minutes of grace Its not a snipe You had your shot",
    "Because I’m an offensively minded player",
    "Roaring mood is mid",
    "Character Issue Dragapult is infecting my whole team",
    "I’d consider a trade But … not with your team",
    "Collusion Scizor dropped and picked up immediately",
    "I want a thorough investigation",
    "The Gaylord Gastrodons select Mandibuzz",
    "With our second round pick the Gaylord Gastrodons select Mega-Lopunny",
    "The Gylord Gastrodons Select Dragapult, somehow",
    "How am I second to last fucking pick tho",
    "I’m sitting here rubbing my hands and licking my lips",
    "The Gaylord Gastrodons would like to announce are in talks with Lunatone, the late round star of last season. It remains to be seen if the demands of the increased contract price can be met by the organization",
    "Coach Choc is tight lipped about the results of that workout",
    "Collusion should be punished with a swift pick kicking to the back of the line",
    "Who will let me trade into a top 4 pick",
    "He was always goated",
    "Damn you really jacked up the price on Lunatone",
    "I think I’ll draft Palafin",
    "I don’t want to be rude but respectfully I don’t really know that a 6 person league playing for no real prize is going to…. Last? Like, I don’t know that its going to have enough active players and all",
    "Mistap isn’t a real word",
    "I did not mean to go blaziken when I did That was a misclick And it literally cost me@playoffs I mean what. The . Fuck.",
    "I am the unluckiest person on earth",
    "@James would you really feel better having it hang over your head all day tomorrow as opposed to just banging it out now? If thats the case then tomorrow is fine But for me I like having shit done and a clear schedule…. Part of why I hate weekend games",
    "You gonna get up at 3 am tomorrow again?",
    "P? Thats because I perfectly read his team, destroyed his lead, and played the endgame to perfection. I won in spite of bad luck, not because of good luck.",
    "Try again hater",
    "Its based across, as I said, hundreds of games with hundreds of game altering bad luck Over and over again. I don’t see this happening to anyone else. But ok , ignore what I’m ACTUALLY saying.",
    "I am the unluckiest draft player of all time Across hundreds of games I challenge you to find anyone who gets as consistently unlucky",
    "We didn’t set a time last time and you ghosted me, so I’d like to not make that same mistake.",
    "@P McGee what time @P McGee Dude @P McGee what gives",
    "@P McGee we supposed to fight",
    "Lost on one turn sleep, never fails.",
    "@Fletcharunt have a preference? @idfkRyan I want you and I to going the other league around the same time by the way So if YOU have a preference speak now please",
    "You just picked the most annoying week to john me",
    "The week starts Sunday",
    "Homie",
    "Makes you think OUR GAME\ Should be at 9",
    "Bro Read. \"I have a draft at 9 and a game After? Before? I have a draft AND A game Now granted Ryan's bum ass cancelled on me Bit I didn't know that at the time What part of \"I have a draft at 9\"",
    "That is NOT what I said I said I have a draft at 9",
    "I specifically said I have a draft at 9 And you're trying to go at 8:55??? Like DUDE",
    "@Fletcharunt dude how long does it take to do a PC",
    "Samky listening to power rankings is pretty pog",
    "Not bad for the lowest power ranked team",
    "See but all the other options left on board suckkk",
    "https://www.youtube.com/watch?v=dqof7Q0GJnU",
    "I think it's a bad team. I lost on the first turn because I did not anticipate the lead or build properly around it. I didn't even think you should have brought that. I mean, you should not have brought Swampert because I have 2 grass types and freeze dry on like on team preview I was mad about that and still am.",
    "Corviknight is so abusable all you have to do is bring fire or electric.",
    "Slither Wing is bait. It's not that good. What happens when you run into a single flying type? My flying type was bad because Mega Absol deleted it, but what do you do against a normal team? What happens when you run into an electric flying type?",
    "Fletch's team is not good. I will put it below Chick's team anytime.",
    "Webs is not a hazard. Hazards damage your opponent.",
    "If I had built Breloom differently, I never lose to this team. I don't think this team is good and I don't expect you to win with it.",
    "I thought you of all people wouldn’t join in the bullying and harassment of me",
    "I really thought better of you. That was a mistake.",
    "@James . Make your choice",
    "I’m being taken to a surprise destination party tomorrow with my friends at like dinner time tomorrow",
    "Its not USELESS just… bad….",
    "Probably home in like…. 40 minutes?",
    "Just piddly pathetic damage and no speed boost",
    "Like shitty knock off and good weather?",
    "¯\\_(ツ)_/¯",
    "Wrong server",
    "Will stay for who the fuck knows how long",
    "I’m legit already built because I didn’t have to reveal anything in the regular season for this matchup lol",
    "I don’t know. Late saturday, probably not TOO late Sunday….",
    "I shall deliver",
    "Yeah I doubt I’m picking you",
    "My odds of being able to do that Saturday are about 1.523836362828% rounded",
    "I gave up part of my vacation to live draft man for this like come on this is so not cool",
    "??? I didn’t mistreat anyone ???",
    "Give me the team back and I’ll happily apologize",
    "Live as in you want us to do nothing but the draft for what? A few hours?",
    "This has been an awful, harmful conversation. You aren't sorry. I came here, was vulnerable, apologized, and you never would have changed your mind anyways. Do not contact me",
    "And it would be so funny to knock palafin out of playoffs just like I’m knocking myself out of playoffs in SDS",
    "Should I be homophobic and pick Whacka",
    "Steven will pick me and I get no choice",
    "Thats so funny",
    "Lol, lmao even",
    "OH WAIT WE GET TO PICK",
    "HEY pickems are supposed to be annony moose 😡",
    "This was clearly your B squad anyways I’ll see you in playoffs when you bring Koko and the real hard hitters",
    "Well you made a decision to try to pivot instead of just clicking switch",
    "You can’t blame that one on RNG like… the u turn chip was useless to you at THAT moment",
    "Well thats your fault for not hard switching",
    "I accidentally did tera rock",
    "And let latios in on me? As if",
    "I had a great tera type in mind that would have ended it quicker",
    "Choc Tera captain stocks 📈📈📈",
    "The shaymin paralyze mattered not",
    "You didn’t kill through light screen",
    "@idfkRyan lets tussle",
    "@idfkRyan I guess I can play on my lunch break since this won’t be a super important game to me",
    "Work is working me to the bone",
    "I will JUST be getting home at 9, if I speed home@from work",
    "As usual! Whaaatttt",
    "No you didn’t",
    "He can’t keep everything alive",
    "+2 252+ Atk Blaziken Flare Blitz vs. 244 HP / 252+ Def Gliscor in Sun: 375-442 (106.5 - 125.5%) -- guaranteed OHKO",
    "@Comeback kid Monday; 6:30pm est or later\nTuesday: Free, may go out to lunch\nWednesday: 11:15pm est or later\nThursday: tentatively 5pm est or later but may be pushed later as it is an abnormal day at work\nFriday: 10:15pm est or later\nSaturday: currently Free, may go out with friends\nSunday: currently free may make plans as well",
    "If I wouyld have known there was no overqwill I could have swept with calm mind again but alas",
    "Like Lunatone was just there to set rocks, toxic something, and die",
    "It arguably made my job easier lol",
    "I’m sorry but the onus is not on me to offer a solution after I’ve already been accommodating. With advanced notice you moved it from Saturday to Sunday, which is all well and good, but then I sat here for some time where you were nowhere to be found so unfortunately at this point yeah, I will just be claiming. Good luck with the rest of the season and maybe I’ll see you in playoffs",
    "I was willing to play a later time but you weren’t like “oh man I missed yesterday and the day before but I CAN go tonight” you didn’t really offer a solution for an extension, so, you know. It makes sense.",
    "lmao",
    "You’re unblocked",
    "It just hurt to have the one person who I thought have my back…… not. Like really hurt",
    "Agree or disagree Shaved dicks ( well, area around) usually look bad"
]